services:
  zookeeper:
    image: ${ZOOKEEPER_IMAGE}
    hostname: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper
    healthcheck:
      test: ["CMD-SHELL", "cub zk-ready localhost:${ZOOKEEPER_PORT} 30"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - single-kafka-network
  kafka:
    image: ${KAFKA_IMAGE}
    hostname: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "${KAFKA_INTERNAL_PORT}:${KAFKA_INTERNAL_PORT}"
      - "${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}"
      - "${KAFKA_JMX_PORT}:${KAFKA_JMX_PORT}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_INTERNAL_PORT},PLAINTEXT_HOST://0.0.0.0:${KAFKA_EXTERNAL_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_INTERNAL_PORT},PLAINTEXT_HOST://${KAFKA_HOST_IP}:${KAFKA_EXTERNAL_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: ${KAFKA_JMX_PORT}
      KAFKA_JMX_HOSTNAME: ${KAFKA_HOST_IP}
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:${KAFKA_INTERNAL_PORT} > /dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
    networks:
      - single-kafka-network
#  kafka-connect:
#    image: confluentinc/cp-kafka-connect:7.0.1
#    ports:
#      - "8083:8083"
#    container_name: kafka-connect
#    environment:
#      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
#      CONNECT_REST_PORT: 8083
#      CONNECT_GROUP_ID: "quickstart-avro"
#      CONNECT_CONFIG_STORAGE_TOPIC: "quickstart-avro-config"
#      CONNECT_OFFSET_STORAGE_TOPIC: "quickstart-avro-offsets"
#      CONNECT_STATUS_STORAGE_TOPIC: "quickstart-avro-status"
#      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
#      CONNECT_LOG4J_ROOT_LOGLEVEL: WARN
#      CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars"
#    depends_on:
#      - kafka
#    volumes:
#      - ./docker-data-files/lib:/etc/kafka-connect/jars # https://www.confluent.io/hub/confluentinc/kafka-connect-jdbc에서 다운 받고 lib/하위의 jar 파일들을 lib폴더하위로 복사
#    networks:
#      - jpasample-network
  kafka-ui:
    image: ${KAFKA_UI_IMAGE}
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "${KAFKA_CLUSTER_NAME}"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka:${KAFKA_INTERNAL_PORT}"
      KAFKA_CLUSTERS_0_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_PORT}"
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    networks:
      - single-kafka-network

networks:
  single-kafka-network:
    driver: bridge

volumes:
  zookeeper-data:
  kafka-data:
