port 7006
cluster-enabled yes
cluster-config-file /data/nodes.conf
cluster-node-timeout 5000
appendonly yes
dir /data
bind 0.0.0.0
protected-mode no
cluster-announce-ip 172.31.0.16
cluster-announce-port 7006
cluster-announce-bus-port 17006
cluster-announce-hostname localhost
cluster-preferred-endpoint-type hostname
