#!/bin/sh
set -eu

TEMPLATE_PATH="${APISIX_TEMPLATE_PATH:-/usr/local/apisix/conf/config-template.yaml}"
OUTPUT_PATH="${APISIX_OUTPUT_PATH:-/usr/local/apisix/conf/config.yaml}"

envsubst '
${APISIX_NODE_LISTEN}
${APISIX_ENABLE_IPV6}
${APISIX_CONTROL_API_PORT}
${APISIX_LOG_LEVEL}
${APISIX_ADMIN_ALLOW_CIDR}
${APISIX_ADMIN_KEY}
${APISIX_VIEWER_KEY}
${APISIX_ETCD_HOST_1}
${APISIX_ETCD_HOST_2}
${APISIX_ETCD_HOST_3}
${APISIX_ETCD_TIMEOUT}
${APISIX_JAVA_XMS}
${APISIX_JAVA_XMX}
${APISIX_SELF_ADMIN_API_URL}
${APISIX_HEALTH_CHECK_INTERVAL}
${APISIX_HEALTH_CHECK_PATH}
${APISIX_HEALTH_EXPECTED_STATUS}
${APISIX_HEALTH_REWRITE_CODE}
${APISIX_HEALTH_REWRITE_BODY}
${APISIX_PROMETHEUS_EXPORT_PORT}
${APISIX_UPSTREAM_HEALTHCHECK_DICT_SIZE}
' < "${TEMPLATE_PATH}" > "${OUTPUT_PATH}"

if [ "$#" -eq 0 ]; then
  set -- docker-start
fi

exec /docker-entrypoint.sh "$@"
