apiVersion: 1

datasources:
  - name: Elasticsearch Logs
    type: elasticsearch
    access: proxy
    url: ${ELASTICSEARCH_URL}
    basicAuth: true
    basicAuthUser: grafana_internal
    secureJsonData:
      basicAuthPassword: ${GRAFANA_INTERNAL_PASSWORD}
    jsonData:
      index: ${GRAFANA_LOG_INDEX_PATTERN}
      timeField: "@timestamp"
      interval: Daily

  - name: Elasticsearch Metrics
    type: elasticsearch
    access: proxy
    url: ${ELASTICSEARCH_URL}
    basicAuth: true
    basicAuthUser: grafana_internal
    secureJsonData:
      basicAuthPassword: ${GRAFANA_INTERNAL_PASSWORD}
    jsonData:
      index: ${GRAFANA_METRIC_INDEX_PATTERN}
      timeField: "@timestamp"
      interval: Daily
