services:
  redis:
    image: redis:${REDIS_VERSION:-7.2.4}
    env_file:
      - .env
    command: ["/bin/sh", "/usr/local/bin/bootstrap-config.sh"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./conf:/seed/redis:ro
      - redis_single_config:/usr/local/etc/redis
      - redis_single_data:/data
      - ./scripts/bootstrap-config.sh:/usr/local/bin/bootstrap-config.sh:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli --user \"$${REDIS_APP_USERNAME}\" --pass \"$${REDIS_APP_PASSWORD}\" PING | grep PONG",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      redis_single_network:

networks:
  redis_single_network:
    driver: bridge

volumes:
  redis_single_config:
  redis_single_data:
