services:
  redis:
    image: redis:7.2.4
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./conf/users.acl:/usr/local/etc/redis/users.acl:ro
      - redis_single_data:/data
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "--user",
          "app",
          "--pass",
          "app-password-123",
          "PING",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      redis_single_network:

networks:
  redis_single_network:
    driver: bridge

volumes:
  redis_single_data:
