port 7004
cluster-enabled yes
cluster-config-file /data/nodes.conf
cluster-node-timeout 5000
appendonly yes
dir /data
bind 0.0.0.0
protected-mode no
cluster-announce-ip 172.31.0.14
cluster-announce-port 7004
cluster-announce-bus-port 17004
cluster-announce-hostname localhost
cluster-preferred-endpoint-type hostname
