# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
receivers:
  # Data sources: traces, metrics, logs
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        # tls: # tls 미사용시 tls부터 주석
        #   cert_file: /etc/otelcol-contrib/server.crt
        #   key_file: /etc/otelcol-contrib/server.key
      http:
        endpoint: 0.0.0.0:4318
        # react 같은 client service에서 적용할때 사용
        # cors:
        #   allowed_origins:
        #     - http://localhost:8080

exporters:
  debug:
  # Compose 내부 서비스명 기준 exporter 엔드포인트입니다.
  otlp_grpc/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlp_grpc/jaeger: # Jaeger supports OTLP directly. The default port for OTLP/gRPC is 4317
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp_http/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp
    tls:
      insecure: true
  otlp_http/loki:
    endpoint: http://loki:3100/otlp

processors:
  batch:

extensions:
  health_check:

connectors:
  spanmetrics:
    dimensions:
      - name: http.status_code
      - name: http.target
      - name: http.url
      - name: http.method
      - name: http.scheme
      - name: http.route
      - name: rpc.grpc.status_code
      - name: rpc.method
      - name: rpc.service
      - name: db.system
      - name: db.statement

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_grpc/jaeger, debug, spanmetrics, otlp_grpc/tempo]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [otlp_http/prometheus, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp_http/loki]
